version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t lokel/deploy:1.0 .
      - docker tag 704183799769.dkr.ecr.ap-southeast-2.amazonaws.com/test1
      - docker tag lokel/deploy:1.0 704183799769.dkr.ecr.ap-southeast-2.amazonaws.com/test1/lokel/deploy:1.0   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 704183799769.dkr.ecr.ap-southeast-2.amazonaws.com/test1/lokel/deploy:1.0
